/*
This file is part of the ORK library.
Full copyright and license terms can be found in the LICENSE.txt file.
*/
#ifndef ORK_ORK_HPP
#	error This header can only be included from ork/ork.hpp!
#endif
#ifdef ORK_TOOLS_GENERATD_HPP
#	error This header can only be included from ork/ork.hpp!
#endif

#ifndef ORK_TOOLS_GENERATD_HPP
#define ORK_TOOLS_GENERATD_HPP


namespace ork {

//These are dumb, brute force macros that are generated by ork_test




}//namespace ork

#endif//ORK_TOOLS_GENERATD_HPP
