/*
This file is part of the ORK library.
Full copyright and license terms can be found in the LICENSE.txt file.
*/
#ifndef ORK_ORK_HPP
#	error This header can only be included from ork/ork.hpp!
#endif
#ifdef ORK_TOOLS_GENERATD_HPP
#	error This header can only be included from ork/ork.hpp!
#endif

#ifndef ORK_TOOLS_GENERATD_HPP
#define ORK_TOOLS_GENERATD_HPP


namespace ork {

//These are dumb, brute force macros that are generated by ork_test


#define ORK_GET_ARG_00_(A0, ...) A0
#define ORK_GET_ARG_01_(A0, A1, ...) A1
#define ORK_GET_ARG_02_(A0, A1, A2, ...) A2
#define ORK_GET_ARG_03_(A0, A1, A2, A3, ...) A3
#define ORK_GET_ARG_04_(A0, A1, A2, A3, A4, ...) A4
#define ORK_GET_ARG_05_(A0, A1, A2, A3, A4, A5, ...) A5
#define ORK_GET_ARG_06_(A0, A1, A2, A3, A4, A5, A6, ...) A6
#define ORK_GET_ARG_07_(A0, A1, A2, A3, A4, A5, A6, A7, ...) A7
#define ORK_GET_ARG_08_(A0, A1, A2, A3, A4, A5, A6, A7, A8, ...) A8
#define ORK_GET_ARG_09_(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, ...) A9
#define ORK_GET_ARG_10_(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, ...) A10
#define ORK_GET_ARG_11_(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, ...) A11
#define ORK_GET_ARG_12_(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, ...) A12
#define ORK_GET_ARG_13_(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, ...) A13
#define ORK_GET_ARG_14_(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, ...) A14
#define ORK_GET_ARG_15_(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, ...) A15
#define ORK_GET_ARG_16_(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, ...) A16
#define ORK_GET_ARG_17_(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, ...) A17
#define ORK_GET_ARG_18_(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, ...) A18
#define ORK_GET_ARG_19_(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, ...) A19
#define ORK_GET_ARG_20_(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, ...) A20
#define ORK_GET_ARG_21_(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21, ...) A21
#define ORK_GET_ARG_22_(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21, A22, ...) A22
#define ORK_GET_ARG_23_(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21, A22, A23, ...) A23
#define ORK_GET_ARG_24_(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21, A22, A23, A24, ...) A24
#define ORK_GET_ARG_25_(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21, A22, A23, A24, A25, ...) A25
#define ORK_GET_ARG_26_(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21, A22, A23, A24, A25, A26, ...) A26
#define ORK_GET_ARG_27_(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21, A22, A23, A24, A25, A26, A27, ...) A27
#define ORK_GET_ARG_28_(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21, A22, A23, A24, A25, A26, A27, A28, ...) A28
#define ORK_GET_ARG_29_(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21, A22, A23, A24, A25, A26, A27, A28, A29, ...) A29
#define ORK_GET_ARG_30_(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21, A22, A23, A24, A25, A26, A27, A28, A29, A30, ...) A30
#define ORK_GET_ARG_31_(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21, A22, A23, A24, A25, A26, A27, A28, A29, A30, A31, ...) A31
#define ORK_GET_ARG_32_(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21, A22, A23, A24, A25, A26, A27, A28, A29, A30, A31, A32, ...) A32
#define ORK_GET_ARG_33_(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21, A22, A23, A24, A25, A26, A27, A28, A29, A30, A31, A32, A33, ...) A33
#define ORK_GET_ARG_34_(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21, A22, A23, A24, A25, A26, A27, A28, A29, A30, A31, A32, A33, A34, ...) A34
#define ORK_GET_ARG_35_(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21, A22, A23, A24, A25, A26, A27, A28, A29, A30, A31, A32, A33, A34, A35, ...) A35
#define ORK_GET_ARG_36_(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21, A22, A23, A24, A25, A26, A27, A28, A29, A30, A31, A32, A33, A34, A35, A36, ...) A36
#define ORK_GET_ARG_37_(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21, A22, A23, A24, A25, A26, A27, A28, A29, A30, A31, A32, A33, A34, A35, A36, A37, ...) A37
#define ORK_GET_ARG_38_(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21, A22, A23, A24, A25, A26, A27, A28, A29, A30, A31, A32, A33, A34, A35, A36, A37, A38, ...) A38
#define ORK_GET_ARG_39_(A0, A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21, A22, A23, A24, A25, A26, A27, A28, A29, A30, A31, A32, A33, A34, A35, A36, A37, A38, A39, ...) A39

#define ORK_ARG_N_(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21, A22, A23, A24, A25, A26, A27, A28, A29, A30, A31, A32, A33, A34, A35, A36, A37, A38, A39, A40, A41, ...) A41

#define ORK_DESCENDING_N_ 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0

#define ORK_INC_0 1
#define ORK_INC_1 2
#define ORK_INC_2 3
#define ORK_INC_3 4
#define ORK_INC_4 5
#define ORK_INC_5 6
#define ORK_INC_6 7
#define ORK_INC_7 8
#define ORK_INC_8 9
#define ORK_INC_9 10
#define ORK_INC_10 11
#define ORK_INC_11 12
#define ORK_INC_12 13
#define ORK_INC_13 14
#define ORK_INC_14 15
#define ORK_INC_15 16
#define ORK_INC_16 17
#define ORK_INC_17 18
#define ORK_INC_18 19
#define ORK_INC_19 20
#define ORK_INC_20 21
#define ORK_INC_21 22
#define ORK_INC_22 23
#define ORK_INC_23 24
#define ORK_INC_24 25
#define ORK_INC_25 26
#define ORK_INC_26 27
#define ORK_INC_27 28
#define ORK_INC_28 29
#define ORK_INC_29 30
#define ORK_INC_30 31
#define ORK_INC_31 32
#define ORK_INC_32 33
#define ORK_INC_33 34
#define ORK_INC_34 35
#define ORK_INC_35 36
#define ORK_INC_36 37
#define ORK_INC_37 38
#define ORK_INC_38 39
#define ORK_INC_39 40
#define ORK_INC_40 41
#define ORK_INC_41 42
#define ORK_INC_42 43
#define ORK_INC_43 44
#define ORK_INC_44 45
#define ORK_INC_45 46
#define ORK_INC_46 47
#define ORK_INC_47 48
#define ORK_INC_48 49
#define ORK_INC_49 50
#define ORK_INC_50 51
#define ORK_INC_51 52
#define ORK_INC_52 53
#define ORK_INC_53 54
#define ORK_INC_54 55
#define ORK_INC_55 56
#define ORK_INC_56 57
#define ORK_INC_57 58
#define ORK_INC_58 59
#define ORK_INC_59 60
#define ORK_INC_60 61
#define ORK_INC_61 62
#define ORK_INC_62 63
#define ORK_INC_63 64
#define ORK_INC_64 65
#define ORK_INC_65 66
#define ORK_INC_66 67
#define ORK_INC_67 68
#define ORK_INC_68 69
#define ORK_INC_69 70
#define ORK_INC_70 71
#define ORK_INC_71 72
#define ORK_INC_72 73
#define ORK_INC_73 74
#define ORK_INC_74 75
#define ORK_INC_75 76
#define ORK_INC_76 77
#define ORK_INC_77 78
#define ORK_INC_78 79
#define ORK_INC_79 80
#define ORK_INC_80 81
#define ORK_INC_81 82
#define ORK_INC_82 83
#define ORK_INC_83 84
#define ORK_INC_84 85
#define ORK_INC_85 86
#define ORK_INC_86 87
#define ORK_INC_87 88
#define ORK_INC_88 89
#define ORK_INC_89 90
#define ORK_INC_90 91
#define ORK_INC_91 92
#define ORK_INC_92 93
#define ORK_INC_93 94
#define ORK_INC_94 95
#define ORK_INC_95 96
#define ORK_INC_96 97
#define ORK_INC_97 98
#define ORK_INC_98 99
#define ORK_INC_99 100
#define ORK_INC_100 101
#define ORK_INC_101 102
#define ORK_INC_102 103
#define ORK_INC_103 104
#define ORK_INC_104 105
#define ORK_INC_105 106
#define ORK_INC_106 107
#define ORK_INC_107 108
#define ORK_INC_108 109
#define ORK_INC_109 110
#define ORK_INC_110 111
#define ORK_INC_111 112
#define ORK_INC_112 113
#define ORK_INC_113 114
#define ORK_INC_114 115
#define ORK_INC_115 116
#define ORK_INC_116 117
#define ORK_INC_117 118
#define ORK_INC_118 119
#define ORK_INC_119 120
#define ORK_INC_120 121
#define ORK_INC_121 122
#define ORK_INC_122 123
#define ORK_INC_123 124
#define ORK_INC_124 125
#define ORK_INC_125 126
#define ORK_INC_126 127
#define ORK_INC_127 128
#define ORK_INC_128 129
#define ORK_INC_129 130
#define ORK_INC_130 131
#define ORK_INC_131 132
#define ORK_INC_132 133
#define ORK_INC_133 134
#define ORK_INC_134 135
#define ORK_INC_135 136
#define ORK_INC_136 137
#define ORK_INC_137 138
#define ORK_INC_138 139
#define ORK_INC_139 140
#define ORK_INC_140 141
#define ORK_INC_141 142
#define ORK_INC_142 143
#define ORK_INC_143 144
#define ORK_INC_144 145
#define ORK_INC_145 146
#define ORK_INC_146 147
#define ORK_INC_147 148
#define ORK_INC_148 149
#define ORK_INC_149 150
#define ORK_INC_150 151
#define ORK_INC_151 152
#define ORK_INC_152 153
#define ORK_INC_153 154
#define ORK_INC_154 155
#define ORK_INC_155 156
#define ORK_INC_156 157
#define ORK_INC_157 158
#define ORK_INC_158 159
#define ORK_INC_159 160
#define ORK_INC_160 161
#define ORK_INC_161 162
#define ORK_INC_162 163
#define ORK_INC_163 164
#define ORK_INC_164 165
#define ORK_INC_165 166
#define ORK_INC_166 167
#define ORK_INC_167 168
#define ORK_INC_168 169
#define ORK_INC_169 170
#define ORK_INC_170 171
#define ORK_INC_171 172
#define ORK_INC_172 173
#define ORK_INC_173 174
#define ORK_INC_174 175
#define ORK_INC_175 176
#define ORK_INC_176 177
#define ORK_INC_177 178
#define ORK_INC_178 179
#define ORK_INC_179 180
#define ORK_INC_180 181
#define ORK_INC_181 182
#define ORK_INC_182 183
#define ORK_INC_183 184
#define ORK_INC_184 185
#define ORK_INC_185 186
#define ORK_INC_186 187
#define ORK_INC_187 188
#define ORK_INC_188 189
#define ORK_INC_189 190
#define ORK_INC_190 191
#define ORK_INC_191 192
#define ORK_INC_192 193
#define ORK_INC_193 194
#define ORK_INC_194 195
#define ORK_INC_195 196
#define ORK_INC_196 197
#define ORK_INC_197 198
#define ORK_INC_198 199
#define ORK_INC_199 200
#define ORK_INC_200 201
#define ORK_INC_201 202
#define ORK_INC_202 203
#define ORK_INC_203 204
#define ORK_INC_204 205
#define ORK_INC_205 206
#define ORK_INC_206 207
#define ORK_INC_207 208
#define ORK_INC_208 209
#define ORK_INC_209 210
#define ORK_INC_210 211
#define ORK_INC_211 212
#define ORK_INC_212 213
#define ORK_INC_213 214
#define ORK_INC_214 215
#define ORK_INC_215 216
#define ORK_INC_216 217
#define ORK_INC_217 218
#define ORK_INC_218 219
#define ORK_INC_219 220
#define ORK_INC_220 221
#define ORK_INC_221 222
#define ORK_INC_222 223
#define ORK_INC_223 224
#define ORK_INC_224 225
#define ORK_INC_225 226
#define ORK_INC_226 227
#define ORK_INC_227 228
#define ORK_INC_228 229
#define ORK_INC_229 230
#define ORK_INC_230 231
#define ORK_INC_231 232
#define ORK_INC_232 233
#define ORK_INC_233 234
#define ORK_INC_234 235
#define ORK_INC_235 236
#define ORK_INC_236 237
#define ORK_INC_237 238
#define ORK_INC_238 239
#define ORK_INC_239 240
#define ORK_INC_240 241
#define ORK_INC_241 242
#define ORK_INC_242 243
#define ORK_INC_243 244
#define ORK_INC_244 245
#define ORK_INC_245 246
#define ORK_INC_246 247
#define ORK_INC_247 248
#define ORK_INC_248 249
#define ORK_INC_249 250
#define ORK_INC_250 251
#define ORK_INC_251 252
#define ORK_INC_252 253
#define ORK_INC_253 254
#define ORK_INC_254 255
#define ORK_INC_255 256

#define ORK_DEC_1 0
#define ORK_DEC_2 1
#define ORK_DEC_3 2
#define ORK_DEC_4 3
#define ORK_DEC_5 4
#define ORK_DEC_6 5
#define ORK_DEC_7 6
#define ORK_DEC_8 7
#define ORK_DEC_9 8
#define ORK_DEC_10 9
#define ORK_DEC_11 10
#define ORK_DEC_12 11
#define ORK_DEC_13 12
#define ORK_DEC_14 13
#define ORK_DEC_15 14
#define ORK_DEC_16 15
#define ORK_DEC_17 16
#define ORK_DEC_18 17
#define ORK_DEC_19 18
#define ORK_DEC_20 19
#define ORK_DEC_21 20
#define ORK_DEC_22 21
#define ORK_DEC_23 22
#define ORK_DEC_24 23
#define ORK_DEC_25 24
#define ORK_DEC_26 25
#define ORK_DEC_27 26
#define ORK_DEC_28 27
#define ORK_DEC_29 28
#define ORK_DEC_30 29
#define ORK_DEC_31 30
#define ORK_DEC_32 31
#define ORK_DEC_33 32
#define ORK_DEC_34 33
#define ORK_DEC_35 34
#define ORK_DEC_36 35
#define ORK_DEC_37 36
#define ORK_DEC_38 37
#define ORK_DEC_39 38
#define ORK_DEC_40 39
#define ORK_DEC_41 40
#define ORK_DEC_42 41
#define ORK_DEC_43 42
#define ORK_DEC_44 43
#define ORK_DEC_45 44
#define ORK_DEC_46 45
#define ORK_DEC_47 46
#define ORK_DEC_48 47
#define ORK_DEC_49 48
#define ORK_DEC_50 49
#define ORK_DEC_51 50
#define ORK_DEC_52 51
#define ORK_DEC_53 52
#define ORK_DEC_54 53
#define ORK_DEC_55 54
#define ORK_DEC_56 55
#define ORK_DEC_57 56
#define ORK_DEC_58 57
#define ORK_DEC_59 58
#define ORK_DEC_60 59
#define ORK_DEC_61 60
#define ORK_DEC_62 61
#define ORK_DEC_63 62
#define ORK_DEC_64 63
#define ORK_DEC_65 64
#define ORK_DEC_66 65
#define ORK_DEC_67 66
#define ORK_DEC_68 67
#define ORK_DEC_69 68
#define ORK_DEC_70 69
#define ORK_DEC_71 70
#define ORK_DEC_72 71
#define ORK_DEC_73 72
#define ORK_DEC_74 73
#define ORK_DEC_75 74
#define ORK_DEC_76 75
#define ORK_DEC_77 76
#define ORK_DEC_78 77
#define ORK_DEC_79 78
#define ORK_DEC_80 79
#define ORK_DEC_81 80
#define ORK_DEC_82 81
#define ORK_DEC_83 82
#define ORK_DEC_84 83
#define ORK_DEC_85 84
#define ORK_DEC_86 85
#define ORK_DEC_87 86
#define ORK_DEC_88 87
#define ORK_DEC_89 88
#define ORK_DEC_90 89
#define ORK_DEC_91 90
#define ORK_DEC_92 91
#define ORK_DEC_93 92
#define ORK_DEC_94 93
#define ORK_DEC_95 94
#define ORK_DEC_96 95
#define ORK_DEC_97 96
#define ORK_DEC_98 97
#define ORK_DEC_99 98
#define ORK_DEC_100 99
#define ORK_DEC_101 100
#define ORK_DEC_102 101
#define ORK_DEC_103 102
#define ORK_DEC_104 103
#define ORK_DEC_105 104
#define ORK_DEC_106 105
#define ORK_DEC_107 106
#define ORK_DEC_108 107
#define ORK_DEC_109 108
#define ORK_DEC_110 109
#define ORK_DEC_111 110
#define ORK_DEC_112 111
#define ORK_DEC_113 112
#define ORK_DEC_114 113
#define ORK_DEC_115 114
#define ORK_DEC_116 115
#define ORK_DEC_117 116
#define ORK_DEC_118 117
#define ORK_DEC_119 118
#define ORK_DEC_120 119
#define ORK_DEC_121 120
#define ORK_DEC_122 121
#define ORK_DEC_123 122
#define ORK_DEC_124 123
#define ORK_DEC_125 124
#define ORK_DEC_126 125
#define ORK_DEC_127 126
#define ORK_DEC_128 127
#define ORK_DEC_129 128
#define ORK_DEC_130 129
#define ORK_DEC_131 130
#define ORK_DEC_132 131
#define ORK_DEC_133 132
#define ORK_DEC_134 133
#define ORK_DEC_135 134
#define ORK_DEC_136 135
#define ORK_DEC_137 136
#define ORK_DEC_138 137
#define ORK_DEC_139 138
#define ORK_DEC_140 139
#define ORK_DEC_141 140
#define ORK_DEC_142 141
#define ORK_DEC_143 142
#define ORK_DEC_144 143
#define ORK_DEC_145 144
#define ORK_DEC_146 145
#define ORK_DEC_147 146
#define ORK_DEC_148 147
#define ORK_DEC_149 148
#define ORK_DEC_150 149
#define ORK_DEC_151 150
#define ORK_DEC_152 151
#define ORK_DEC_153 152
#define ORK_DEC_154 153
#define ORK_DEC_155 154
#define ORK_DEC_156 155
#define ORK_DEC_157 156
#define ORK_DEC_158 157
#define ORK_DEC_159 158
#define ORK_DEC_160 159
#define ORK_DEC_161 160
#define ORK_DEC_162 161
#define ORK_DEC_163 162
#define ORK_DEC_164 163
#define ORK_DEC_165 164
#define ORK_DEC_166 165
#define ORK_DEC_167 166
#define ORK_DEC_168 167
#define ORK_DEC_169 168
#define ORK_DEC_170 169
#define ORK_DEC_171 170
#define ORK_DEC_172 171
#define ORK_DEC_173 172
#define ORK_DEC_174 173
#define ORK_DEC_175 174
#define ORK_DEC_176 175
#define ORK_DEC_177 176
#define ORK_DEC_178 177
#define ORK_DEC_179 178
#define ORK_DEC_180 179
#define ORK_DEC_181 180
#define ORK_DEC_182 181
#define ORK_DEC_183 182
#define ORK_DEC_184 183
#define ORK_DEC_185 184
#define ORK_DEC_186 185
#define ORK_DEC_187 186
#define ORK_DEC_188 187
#define ORK_DEC_189 188
#define ORK_DEC_190 189
#define ORK_DEC_191 190
#define ORK_DEC_192 191
#define ORK_DEC_193 192
#define ORK_DEC_194 193
#define ORK_DEC_195 194
#define ORK_DEC_196 195
#define ORK_DEC_197 196
#define ORK_DEC_198 197
#define ORK_DEC_199 198
#define ORK_DEC_200 199
#define ORK_DEC_201 200
#define ORK_DEC_202 201
#define ORK_DEC_203 202
#define ORK_DEC_204 203
#define ORK_DEC_205 204
#define ORK_DEC_206 205
#define ORK_DEC_207 206
#define ORK_DEC_208 207
#define ORK_DEC_209 208
#define ORK_DEC_210 209
#define ORK_DEC_211 210
#define ORK_DEC_212 211
#define ORK_DEC_213 212
#define ORK_DEC_214 213
#define ORK_DEC_215 214
#define ORK_DEC_216 215
#define ORK_DEC_217 216
#define ORK_DEC_218 217
#define ORK_DEC_219 218
#define ORK_DEC_220 219
#define ORK_DEC_221 220
#define ORK_DEC_222 221
#define ORK_DEC_223 222
#define ORK_DEC_224 223
#define ORK_DEC_225 224
#define ORK_DEC_226 225
#define ORK_DEC_227 226
#define ORK_DEC_228 227
#define ORK_DEC_229 228
#define ORK_DEC_230 229
#define ORK_DEC_231 230
#define ORK_DEC_232 231
#define ORK_DEC_233 232
#define ORK_DEC_234 233
#define ORK_DEC_235 234
#define ORK_DEC_236 235
#define ORK_DEC_237 236
#define ORK_DEC_238 237
#define ORK_DEC_239 238
#define ORK_DEC_240 239
#define ORK_DEC_241 240
#define ORK_DEC_242 241
#define ORK_DEC_243 242
#define ORK_DEC_244 243
#define ORK_DEC_245 244
#define ORK_DEC_246 245
#define ORK_DEC_247 246
#define ORK_DEC_248 247
#define ORK_DEC_249 248
#define ORK_DEC_250 249
#define ORK_DEC_251 250
#define ORK_DEC_252 251
#define ORK_DEC_253 252
#define ORK_DEC_254 253
#define ORK_DEC_255 254
#define ORK_DEC_256 255


}//namespace ork

#endif//ORK_TOOLS_GENERATD_HPP
