
version: 0.2.{build}

clone_folder: "c:/projects/ork"

image: Visual Studio 2017

environment:
  matrix:
    - ORK_UNICODE: OFF
      VS_VERSION: 14 2015
      VS_TOOLSET: 140
    - ORK_UNICODE: ON
      VS_VERSION: 15 2017
      VS_TOOLSET: 141

install:
  - git clone "https://github.com/calsev/boost_1_66_0_vc_%VS_TOOLSET%_x64" "c:/projects/boost_%VS_TOOLSET%"
  - git clone "https://github.com/catchorg/Catch2" "c:/projects/catch"
  - git clone "https://github.com/g-truc/glm" "c:/projects/glm"
  - git clone "https://github.com/nlohmann/json" "c:/projects/json"
  - git clone "https://github.com/zeux/pugixml" "c:/projects/pugi"
  - git clone "https://github.com/jbeder/yaml-cpp" "c:/projects/yaml"

before_build:
  - cd "c:/projects/catch"
  - git checkout v1.9.7
  - cd "c:/projects/glm"
  - git checkout 0.9.8.5
  - cd "c:/projects/json"
  - git checkout v3.0.1
  - cd "c:/projects/pugi"
  - git checkout v1.8.1
  - cd "c:/projects/yaml"
  - git checkout release-0.5.3
  - mkdir "c:/projects/ork_build_%VS_TOOLSET%"
  - mkdir "c:/projects/ork_test_%VS_TOOLSET%"
  - cd "c:/projects"
  - dir
  - cd "c:/projects/ork_build_%VS_TOOLSET%"
  - cmake -G "Visual Studio %VS_VERSION% Win64" -T v%VS_TOOLSET% "c:/projects/ork/test"

platform:
  - x64

configuration:
  - Debug
  - Release
