
version: 0.2.{build}

clone_folder: c:\projects\ork

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      BOOST_URL: "https://github.com/calsev/boost_1_66_0_vc_140_x64"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      BOOST_URL: "https://github.com/calsev/boost_1_66_0_vc_141_x64"

install:
  - echo Boost URL=%BOOST_URL%
  - git clone %BOOST_URL% "c:\projects\boost"
  - git clone "https://github.com/g-truc/glm" "c:\projects\glm"
  - git clone "https://github.com/nlohmann/json" "c:\projects\json"
  - git clone "https://github.com/zeux/pugixml" "c:\projects\pugi"
  - git clone "https://github.com/jbeder/yaml-cpp" "c:\projects\yaml"

before_build:
  - cd "c:\projects\glm"
  - git checkout 0.9.8.5
  - cd "c:\projects\json"
  - git checkout v3.0.1
  - cd "c:\projects\pugi"
  - git checkout v1.8.1
  - cd "c:\projects\yaml"
  - git checkout version-0.5.3
  - mkdir "c:\projects\ork_build"
  - cd "c:\projects\ork_build"
  - cmake "c:\projects\ork\test"
  
platform:
  - x64

configuration:
  - Debug
  - Release
